### ISSUE TITLE
close button (0.1.16)

### ISSUE THREAD

**Issue by nearcbw** [perfilrobo/hexbot#43]
BUG on close button (0.1.16) no work

**Comment by gresendesa** [comment]
Try to close the current tab and open another tab. I guess it will be enough. I've changed some core attributes (see /libraries/classes/Bot.js) that are not instantly loaded unless you open another tab.

If the problem persists, notify us again.

**Comment by nearcbw** [comment]
Tested on all pages, the button still does not work

**Comment by gresendesa** [comment]
Ok. Could you send me the error logs? Just press f12 then copy the errors and paste them here.

**Comment by nearcbw** [comment]
agora que vi, você é brasileiro sdfnsldfnklsdn
então o erro que dá sobre o bot é o seguinte

 ( extension://hjdemmoplbompmdfjmbfddcimhmmmkgl/controllers/controlPanel.js:12 Uncaught TypeError: Cannot set property 'value' of null  )

e bem que você poderia traduzir o bot pra PT né dkfnsldk meu inglês é basico...

**Comment by gresendesa** [comment]
Hehe. Pois é, sou de Brasília.
Ow, estranho isso, tá funcionando perfeitamente pra mim. Faz assim:
Vou falar em inglês, senão a galera não entende.

This error shows up when you have a textfield defined internally but without the DOM with the respective identifier. For sure your browser is storing conflicting cache. Mostly the problem is solved opening a new tab. If nothing happens remove the browser cache and try again. For more information (in portuguese ;), email me. gresendesa@gmail.com

**Comment by nearcbw** [comment]
de uma olhada no seu email
